### ISSUE TITLE
Enhancement: Add evaluation of Chunking Strategy using Chroma Embeddings

### ISSUE THREAD

**Issue by rmusser01** [rmusser01/tldw#283]
https://github.com/brandonstarxel/chunking_evaluation

**Comment by rmusser01** [comment]
Nope
``
Traceback (most recent call last):
  File "C:\Users\~tldw\App_Function_Libraries\RAG\eval_Chroma_Embeddings.py", line 126, in <module>
    chunk_results = evaluation.run(custom_chunker, custom_ef)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~tldw\venv\Lib\site-packages\chunking_evaluation\evaluation_framework\base_evaluation.py", line 350, in run
    collection = self._chunker_to_collection(chunker, embedding_function)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~tldw\venv\Lib\site-packages\chunking_evaluation\evaluation_framework\base_evaluation.py", line 293, in _chunker_to_collection
    docs, metas = self._get_chunks_and_metadata(chunker)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~tldw\venv\Lib\site-packages\chunking_evaluation\evaluation_framework\base_evaluation.py", line 129, in _get_chunks_and_metadata
    corpus = file.read()
             ^^^^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 313: character maps to <undefined>
```
