### ISSUE TITLE
Issue: Fix transcription issue

### ISSUE THREAD

**Issue by rmusser01** [rmusser01/tldw#4]
When performing transcription, the software does not successfully perform transcription.

Instead, it gives the following error:
```
Traceback (most recent call last):
  File "C:\Users\<username>\Working\tldw\diarize.py", line 82, in speech_to_text
    segments_raw, info = model.transcribe(audio_file, **transcribe_options)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Roaming\Python\Python312\site-packages\faster_whisper\transcribe.py", line 294, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Roaming\Python\Python312\site-packages\faster_whisper\audio.py", line 46, in decode_audio
    with av.open(input_file, mode="r", metadata_errors="ignore") as container:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "av\\container\\core.pyx", line 401, in av.container.core.open
  File "av\\container\\core.pyx", line 265, in av.container.core.Container.__cinit__
  File "av\\container\\core.pyx", line 285, in av.container.core.Container.err_check
  File "av\\error.pyx", line 336, in av.error.err_check
av.error.FileNotFoundError: [Errno 2] No such file or directory: 'A Red Teamer’s Guide to Building a Blue Team - Mark Bayley [ifImQaHEhqY].wav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<username>\Working\tldw\diarize.py", line 227, in <module>
    fire.Fire(main)
  File "C:\Python312\Lib\site-packages\fire\core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\fire\core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\fire\core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\Working\tldw\diarize.py", line 221, in main
    segments = speech_to_text(video_path, whisper_model=whisper_model, vad_filter=vad_filter)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\Working\tldw\diarize.py", line 101, in speech_to_text
    raise RuntimeError("Error transcribing.")
RuntimeError: Error transcribing.
```

Identify and resolve the above issue so that the software may be used without issue.

**Comment by rmusser01** [comment]
Resolved.
